project:
  type: website

website:
  title: "Madeline Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: coursework.qmd
        text: Coursework

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true



