project:
  type: website
  resources: 
    - madelinekimresume.pdf

website:
  title: "Madeline Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: coursework.qmd
        text: Coursework

format:
  html:
    theme:
      - solar
      - brand
    fontcolor: white
    css: styles.css
    toc: true



